Repository JuliaGPU/CUDAnative.jl, pull requests merged in 2019-02, with the labels that each got.

#339 add threadfence intrinsics
  docs/src/lib/device/intrinsics.md
  src/device/cuda_intrinsics.jl
  src/device/cuda_intrinsics/misc.jl
  src/device/cuda_intrinsics/synchronization.jl
  test/device/intrinsics.jl
Labels: CUDA support

#348 Fix deprecation warning.
  src/compiler/irgen.jl
Labels: bug

#343 Check for OOM when doing malloc.
  src/device/runtime_intrinsics.jl
Labels: bug

#341 Fix safe_fn
  src/compiler/irgen.jl
  test/codegen.jl
Labels: bug

#358 Add Synchronisation Barriers (count, and, or)
  src/device/cuda_intrinsics/synchronization.jl
  test/device/intrinsics.jl
Labels: CUDA support, enhancement
