Repository JuliaGPU/CUDAnative.jl, pull requests merged in 2019-04, with the labels that each got.

#369 Improve performance of IR rewriting pass
  REQUIRE
  src/compiler.jl
  src/compiler/irgen.jl
  src/compiler/optim.jl
  src/execution.jl
Labels: codegen, performance

#373 Support for resetting the device.
  src/init.jl
  test/runtests.jl
Labels: CUDA support

#379 llvmcall tuple arguments need to be a literal.
  src/device/cuda/cooperative_groups.jl
  src/device/cuda/dynamic_parallelism.jl
  src/execution.jl
Labels: bug, codegen

#378 explain why an argument is not isbits
  src/compiler/validation.jl
  test/codegen.jl
Labels: enhancement

#382 Detect unbound typevars.
  src/compiler/driver.jl
  test/codegen.jl
Labels: enhancement

#388 Add runtime functions to box floating point values.
  src/device/runtime.jl
  test/codegen.jl
Labels: bug, codegen

#370 Support atomics
  examples/reduce/benchmark.jl
  examples/reduce/reduce.cu
  examples/reduce/reduce.jl
  src/device/array.jl
  src/device/cuda.jl
  src/device/cuda/atomics.jl
  src/device/pointer.jl
  test/device/cuda.jl
Labels: CUDA support, enhancement

#390 guard against types that have no fieldcount
  src/compiler/validation.jl
  test/codegen.jl
Labels: bug

#392 Fix running without CUDA
  src/compiler/driver.jl
  src/compiler/rtlib.jl
  src/init.jl
  src/reflection.jl
  test/codegen.jl
  test/device/codegen.jl
  test/device/cuda.jl
Labels: enhancement

#394 pow function for exponet is Int64
  src/device/cuda/math.jl
  test/device/cuda.jl
Labels: enhancement

#395 Partially cached compilation
  src/compiler/irgen.jl
Labels: codegen, performance
