Repository JuliaGPU/CUDAnative.jl, pull requests merged in 2019-10, with the labels that each got.

#445 Add some more complex operations
  src/device/cuda/math.jl
Labels: enhancement

#472 Fix methoderror generation.
  src/execution.jl
Labels: bug

#474 Use a module exception flag instead of trapping the GPU.
  Manifest.toml
  src/CUDAnative.jl
  src/compiler/driver.jl
  src/compiler/irgen.jl
  src/device/runtime.jl
  src/exceptions.jl
  src/execution.jl
  src/init.jl
  test/device/execution.jl
Labels: codegen, enhancement

#479 Use trap for exceptions on older GPUs.
  src/compiler/irgen.jl
Labels: bug

#478 Adapt to CUDAdrv.jl#167
  .gitlab-ci.yml
  Manifest.toml
  test/array.jl
  test/device/codegen.jl
  test/device/execution.jl
  test/device/pointer.jl
Labels: enhancement

#481 Support for device-side stream creation (for dynamic parallelism)
  .gitlab-ci.yml
  Project.toml
  src/compiler/validation.jl
  src/device/cuda.jl
  src/device/cuda/cooperative_groups.jl
  src/device/cuda/dynamic_parallelism.jl
  src/device/cuda/libcudadevrt.jl
  src/device/cuda/libcudadevrt_common.jl
  src/execution.jl
  test/codegen.jl
  test/device/execution.jl
Labels: CUDA support, enhancement, performance
