Repository JuliaGPU/CUDAnative.jl, pull requests merged in 2020-02, with the labels that each got.

#473 Add autogenerated wrappers for CUPTI and NVTX
  codecov.yml
  res/.gitignore
  res/Manifest.toml
  res/Project.toml
  res/patches/nvtx_aliases.patch
  res/patches/nvtx_macro.patch
  res/patches/nvtx_unions.patch
  res/wrap.jl
  src/CUDAnative.jl
  src/compatibility.jl
  src/cupti/CUPTI.jl
  src/cupti/error.jl
  src/cupti/libcupti.jl
  src/cupti/libcupti_common.jl
  src/nvtx/NVTX.jl
  src/nvtx/highlevel.jl
  src/nvtx/libnvtx.jl
  src/nvtx/libnvtx_common.jl
  src/reflection.jl
  test/runtests.jl
Labels: CUDA support

#400 Make the kernel transform mandatory
  src/compiler/driver.jl
  src/compiler/irgen.jl
  src/compiler/optim.jl
  test/device/execution.jl
Labels: enhancement

#554 Run the inliner at the end of the pipeline.
  src/compiler/irgen.jl
  src/compiler/optim.jl
  src/compiler/rtlib.jl
  test/codegen.jl
Labels: performance

#492 Use BinaryBuilder
  .gitlab-ci.yml
  Artifacts.toml
  Manifest.toml
  Project.toml
  src/CUDAnative.jl
  src/bindeps.jl
  src/compiler/rtlib.jl
  src/cupti/CUPTI.jl
  src/nvtx/NVTX.jl
  test/runtests.jl
Labels: enhancement

#559 Mangle names like C++ does.
  src/compiler/common.jl
  src/compiler/driver.jl
  src/compiler/irgen.jl
  src/utils.jl
  test/codegen.jl
Labels: codegen, enhancement
